spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
server:
  port: 12354